# -*- coding: utf-8 -*-
"""
Created on Fri Apr  1 11:14:50 2022

@author: Sayali
"""


HamNoSysText = {
    "0":["hamceeall","hamextfingerul","hampalmd","hamshoulders","hamparbegin","hammovedr","hamsmallmod","hamreplace","hampinchall","hamparend"],
    "1":["hamfinger2","hamthumbacrossmod","hamextfingeru","hampalmu","hamchest","hamclose","hammoveo","hamsmallmod"],
    "2":["hamfinger23spread","hamthumbacrossmod","hamextfingeru","hampalmu","hamchest","hamclose","hammoveo","hamsmallmod"],
    "3":["hamfinger2345","hamthumbacrossmod","hampinky","hamdoublebent","hamextfingeru","hampalmu","hamchest","hamclose","hammoveo","hamsmallmod"],
    "4":["hamfinger2345","hamthumbacrossmod","hamextfingeru","hampalmu","hamchest","hamclose","hammoveo","hamsmallmod"],
    "5":["hamfinger2345","hamthumboutmod","hamextfingeru","hampalmu","hamchest","hamclose","hammoveo","hamsmallmod"],
    "6":["hamfist","hamthumboutmod","hamfingerhookmod","hamextfingerl","hampalml","hamchest","hamclose","hammoveo","hamsmallmod"],
    "7":["hamflathand","hamthumboutmod","hammiddlefinger","hamfingerhookmod","hamringfinger","hamfingerhookmod","hampinky","hamfingerhookmod","hamextfingerl","hampalml","hamchest","hamclose","hammoveo","hamsmallmod"],
    "8":["hamflathand","hamthumboutmod","hamringfinger","hamfingerhookmod","hampinky","hamfingerhookmod","hamextfingerl","hampalml","hamchest","hamclose","hammoveo","hamsmallmod"],
    "9":["hamflathand","hamthumbacrossmod","hamextfingerl","hampalml","hamchest","hamclose"],
    "a":["hamsymmpar", "hamfist", "hamthumboutmod", "hamextfingeru", "hampalmd", "hamtouch", "hamchest", "hamnomotion"],
    "b":["hamsymmlr", "hampinch12open", "hamextfingeru", "hampalml", "hamparbegin", "hamfingertip", "hamthumb", "hamindexfinger", "hamplus", "hamfingertip", "hamthumb", "hamindexfinger", "hamparend", "hamtouch", "hamchest", "hamclose"],
    "c":["hamcee12", "hamextfingeru", "hampalml", "hamchest", "hambetween", "hamchest", "hamlrat"],
    "d":["hamparbegin", "hamcee12", "hamplus", "hamfinger2", "hamthumbacrossmod", "hamparend", "hamparbegin", "hamextfingeru", "hampalml", "hamplus", "hamextfingeru",	"hampalmr",	"hamparend", "hamparbegin", "hamfingerside", "hamindexfinger", "hamplus", "hamfingertip", "hamthumb", "hamindexfinger", "hamparend", "hamtouch", "hamlrat", "hamchest", "hambetween", "hamchest"],
    "f":["hamsymmlr", "hamfinger23", "hamthumbacrossmod", "hamparbegin", "hamextfingerol", "hampalmd", "hambetween", "hampalmdl", "hamplus", "hamextfingeror", "hampalmd", "hambetween", "hampalmdr", "hamparend", "hamparbegin", "hamshoulders", "hambetween", "hamchest", "hamlrat", "hamplus", "hamlrbeside", "hamstomach", "hambetween", "hamchest", "hamparend", "hammoved", "hamsmallmod", "hamparbegin", "hamfingermidjoint", "hamindexfinger", "hammiddlefinger", "hamplus", "hamfingerpad", "hamindexfinger", "hammiddlefinger", "hamparend", "hamtouch"],
    "g":["hamfist", "hamthumbacrossmod", "hamparbegin", "hamextfingerl", "hampalml", "hamplus", "hamextfingerr", "hampalmr", "hamparend", "hamparbegin", "hamthumbside", "hamplus", "hampinkyside", "hamparend", "hamtouch", "hamchest", "hamclose"],
    "h":["hamflathand", "hamthumboutmod", "hamparbegin", "hamextfingerol", "hampalmd", "hamplus", "hamextfingeror", "hampalmu", "hamparend", "hamparbegin", "hampalm", "hamplus", "hampalm", "hamparend", "hamtouch", "hamstomach", "hamclose", "hammoveor"],
    "k":["hamparbegin", "hamfinger2", "hamthumbacrossmod", "hamfingerhookmod", "hamplus", "hamfinger2", "hamthumbacrossmod", "hamparend", "hamparbegin", "hamextfingerol", "hambetween", "hamextfingerl", "hampalmd", "hamplus", "hamextfingeru", "hampalmr", "hamparend", "hamparbegin", "hamfingernail", "hamindexfinger", "hamplus", "hamfingermidjoint", "hamindexfinger", "hamparend", "hamtouch", "hamchest"],
    "m":["hamparbegin", "hamfinger23", "hamthumbacrossmod", "hamindexfinger", "hammiddlefinger","hamringfinger", "hamplus", "hamflathand", "hamthumboutmod", "hamparend", "hamparbegin", "hamextfingerol", "hampalmd", "hamplus", "hamextfingeror", "hampalmu", "hambetween", "hampalmur", "hamparend", "hamparbegin", "hampalm", "hamplus", "hamfingerpad", "hamindexfinger", "hamparend", "hamtouch", "hamlrat", "hamchest", "hambetween", "hamchest", "hamclose"],
    "n":["hamparbegin", "hamfinger23", "hamthumbacrossmod", "hamplus", "hamflathand", "hamthumboutmod", "hamparend", "hamparbegin", "hamextfingerol", "hampalmd", "hamplus", "hamextfingeror", "hampalmu", "hambetween", "hampalmur", "hamparend", "hamparbegin", "hampalm", "hamplus", "hamfingerpad", "hamindexfinger", "hamparend", "hamtouch", "hamlrat", "hamchest", "hambetween", "hamchest", "hamclose"],
    "p":["hamparbegin", "hampinch12open", "hamplus", "hamfinger2", "hamthumbacrossmod", "hamparend", "hamparbegin", "hamextfingeru", "hampalml", "hamplus", "hamextfingeru", "hambetween", "hamextfingerur", "hampalmd", "hamparend", "hamparbegin", "hamindexfinger", "hamfingertip", "hamplus", "hamthumb", "hamindexfinger", "hamfingertip", "hamparend", "hamtouch", "hamshoulders", "hamclose"],
    "q":["hamparbegin", "hamfinger2", "hamfingerbendmod", "hamplus", "hampinch12open", "hamparend", "hamparbegin", "hamextfingeru", "hampalmd", "hambetween", "hampalmdl", "hamplus", "hamextfingeru", "hambetween", "hamextfingerr", "hampalmd", "hamparend", "hamparbegin", "hamfingerpad", "hamindexfinger", "hamplus", "hamfingermidjoint", "hamindexfinger", "hamparend", "hamtouch"],
  "alone":["hamfinger2", "hamextfingeru", "hampalmu", "hamshouldertop", "hamlrat", "hamcircleu", "hammoveo", "hamsmallmod"],
  "about":["hamsymmlr", "hamalternatingmotion", "hamfinger2", "hamextfingerl", "hampalml", "hamparbegin","hamfingerside","hamindexfinger","hamplus","hamfingerside","hamindexfinger","hamparend","hamtouch","hamchest", "hamcircleo", "hamtouch"],
  "accept":["hamsymmlr", "hamfinger2345", "hamextfingerl", "hampalml", "hamchest", "hamparbegin", "hamreplace", "hamflathand", "hamextfingeril", "hampalmdr", "hamparend", "hamchest", "hamtouch"],
  "across":["hamparbegin", "hamflathand", "hamthumboutmod", "hamplus", "hamflathand", "hamthumboutmod", "hamparend", "hamparbegin", "hamextfingerol", "hamplus", "hamextfingeror", "hamparend", "hamparbegin", "hampalml", "hamplus", "hampalmd", "hamparend", "hammoveol", "hamarcu", "hamparbegin", "hampinkyside", "hamplus", "hamwristback", "hamparend", "hamclose"],
  "after":["hamflathand", "hamthumboutmod", "hamextfingerl", "hampalml", "hamchest", "hamreplace", "hamextfingerl", "hampalmu"],
  "afternoon":["hamfinger2345", "hamthumboutmod", "hamfingerbendmod", "hamextfingerul", "hampalmd", "hamheadtop", "hamlrat", "hamnodding"],
  "angry":["hamfinger2345", "hamfingerbendmod", "hamthumboutmod", "hamextfingeru", "hampalml", "hamear", "hamtouch", "hammover", "hamreplace", "hamfinger23", "hamthumbacrossmod", "hampalml", "hammover", "hamreplace", "hamfinger2345", "hamthumb", "hamfingerbendmod", "hampinky", "hamfingerbendmod", "hampalml"],
  "car":["hamsymmlr","hamfinger2","hamthumboutmod","hamfingerbendmod", "hamextfingero","hampalmdl", "hamchest","hammoved","hamarcr", "hamsmallmod","hammoveu","hamarcr","hamsmallmod","hammoved","hamarcr","hamsmallmod"],
  "cut":["hamparbegin","hamfinger23spread","hamplus","hamflathand","hamthumbacrossmod","hamparend","hamparbegin","hamextfingerol","hamplus","hamextfingerr","hamparend","hamparbegin","hampalml","hamplus","hampalmu","hamparend","hamparbegin","hamfingertip","hammiddlefinger","hamplus","hamfingertip","hammiddlefinger","hamparend","hamclose","hamchest","hamclose","hammoveol","hammoveol","hammoveuo"],
  "certificate":["hamparbegin","hamfist","hamplus","hamfist","hamparend","hamparbegin","hamextfingerol","hamplus","hamextfingeru","hamparend","hamparbegin","hampalmd","hamplus","hampalmd","hamparend","hamparbegin","hamthumbside","hamplus","hamthumbside","hamparend","hamclose","hamlrat","hamshoulders","hammoved","hamlargemod"],
  "child":["hamflathand","hamthumboutmod","hamextfingero","hampalmd","hamchest","hamparbegin","hamreplace","hamextfingero","hambetween","hamextfingeror","hamchest","hamlrat","hammoveu","hamarcl","hamparend"],
  "cinema":["hampinchall","hamextfingeru","hampalml","hameyes","hamparbegin","hamreplace","hamfinger23","hamthumbacrossmod","hamextfingeruo","hampalmdl","hamneck","hamlrat","hamparend"],
  "cook":["hampinch12","hamextfingeru","hampalmu","hamteeth","hamclose","hamparbegin","hamreplace","hamfist","hamextfingerd","hampalmd","hamchest",	"hamparend","hamstircw","hamfast","hamrepeatfromstart"],
  "cricket":["hamsymmpar","hamparbegin","hamflathand","hamplus","hamflathand","hamparend","hamparbegin","hamextfingeru","hamplus","hamextfingeru","hamparend","hamparbegin","hampalml","hamplus","hampalmr","hamparend","hamparbegin","hampalm","hamplus","hampalm","hamparend","hamtouch","hamshouldertop","hamlrat","hammover","hamreplace","hamextfingeror","hamtouch","hammoved","hamlargemod","hamarcr","hamlargemod","hamtouch","hamchest"],
  "cry":["hamfinger23spread","hamextfingerui","hampalmd","hameyes","hammoved","hamrepeatfromstartseveral"],
  "cycle":[	"hamsymmlr","hamfingerstraightmod","hamalternatingmotion","hamfist","hamextfingero","hampalmd","hamchest","hamcircleo","hamsmallmod","hamrepeatfromstartseveral"],
  "deaf":["hamfinger23", "hamextfingerui", "hampalmu", "hamear", "hamtouch", "hammoveu"],
  "desk":["hamsymmlr","hamcee12","hamextfingero","hampalmd","hamparbegin","hamfingerside","hamindexfinger","hammiddlefinger","hamplus","hamfingerside","hamindexfinger","hammiddlefinger","hamparend","hamtouch","hammover"],
  "decrease":["hamflathand","hamthumboutmod","hamfingerbendmod","hamextfingeru","hampalmd","hamshouldertop","hamlrat","hamclose","hamparbegin","hamreplace","hampinchall","hamfingerstraightmod","hammoved","hamslow","hamparend"],
  "discuss":["hamfinger2","hamextfingeru","hampalmdl","hamshoulders","hamclose","hammovedo"],
  "drinking":["hamfist","hamthumboutmod","hamextfingeru","hampalml","hamchin","hamseqbegin","hamclose","hamthumb","hamseqend","hamreplace","hamfist","hamthumboutmod","hamextfingeru","hambetween","hamextfingeri","hampalml","hamchin","hamseqbegin","hamclose","hamthumb","hamseqend"],
  "encourage":["hamsymmlr","hamfinger2345","hamthumboutmod","hamextfingero","hampalmul","hamstomach","hammoveu","hamarcu","hamsmallmod","hamrepeatfromstartseveral"],
  "evening":["hamfinger2345", "hamextfingeru", "hampalmu", "hamshoulders", "hamparbegin", "hamreplace", "hamflathand", "hamthumbacrossmod", "hamchest", "hamparend"],
  "go":["hamflathand","hamthumboutmod","hamextfingerol","hampalml","hamshoulders","hamclose","hamparbegin","hammover","hamlargemod","hamarcd","hamlargemod","hamreplace","hamflathand","hamextfingeru","hampalmd","hamparend"],
  "good":["hamsymmlr", "hamfist", "hamthumboutmod", "hamextfingero", "hampalml", "hamchest", "hamclose", "hammovedo"],
  "he":["hamfinger2", "hamthumboutmod", "hamfingerstraightmod", "hambetween", "hamfinger2", "hamthumbopenmod", "hamfingerstraightmod", "hamextfingeru", "hampalml", "hamnostrils", "hamlrat", "hambetween", "hamlips", "hamlrat", "hamseqbegin", "hamtouch", "hamfingertip", "hamindexfinger", "hamseqend", "hamparbegin", "hamreplace", "hamfinger2", "hamthumbacrossmod", "hamextfingero", "hampalml", "hamchest", "hamlrat", "hambetween", "hamchest", "hamparend"],
  "her":["hamfinger2", "hamfingerbendmod", "hamextfingeru", "hampalmul", "hamnose", "hamtouch", "hammoveo", "hamlargemod", "hamreplace", "hamfinger2", "hamextfingeror", "hampalml"],
  "hungry":["hamflathand", "hamthumboutmod", "hamextfingeri", "hampalmu", "hamstomach", "hammovei", "hammovei"],
  "i":["hamfinger2","hamthumbacrossmod","hamextfingeril","hampalmr","hamchest","hamtouch"],
  "morning":["hampinchall","hamextfingero","hampalmu","hamstomach","hamlrat","hamparbegin","hammoveu","hamreplace","hamfinger2345","hamthumboutmod","hamextfingero","hampalmu","hamparend","hamhead","hamlrat"],
  "mother":["hamfinger2","hamthumbacrossmod","hambetween","hamfinger2","hamfingerstraightmod","hamextfingeru","hampalml","hambetween","hampalmul","hamnose","hamlrat","hambetween","hamnose","hamseqbegin","hamtouch","hamfingerpad","hamindexfinger","hamseqend"],
  "my":["hamfinger2","hamthumbacrossmod","hamextfingeri","hampalmr","hamchest","hamtouch"],
  "namaste":["hamsymmlr","hamflathand","hamthumboutmod","hamextfingeru","hampalml","hamchest","hamseqbegin","hamtouch","hamfingertip","hammiddlefinger","hamseqend","hammoveo","hamsmallmod","hamslow"],
  "never":["hamsymmlr","hamparbegin","hamflathand","hamplus","hamflathand","hamparend","hamparbegin","hamextfingeruo","hamplus","hamextfingeruo","hamparend","hamparbegin","hampalmd","hamplus","hampalmd","hamparend","hamchest","hamclose","hammover"],
  "night":["hamfinger2345", "hamextfingeru", "hampalmu", "hamshoulders", "hammoved", "hamreplace", "hampinch12", "hamstomach"],
  "play":["hamsymmlr", "hamalternatingmotion", "hamfinger2345", "hamthumboutmod", "hamindexfinger", "hamdoublehooked", "hammiddlefinger", "hamdoublehooked", "hamringfinger", "hamdoublehooked", "hamextfingerl", "hampalml", "hamshoulders", "hamparbegin", "hammoveo", "hamtwisting", "hamlargemod", "hamparend"],
  "potato":["hamfinger2345", "hamthumbopenmod", "hamfingerbendmod", "hamringfinger", "hamdoublehooked", "hampinky", "hamdoublehooked", "hamextfingero", "hambetween", "hamextfingeru", "hampalmul", "hamchest", "hamtwisting"],
  "she":["hamfinger2","hamthumbacrossmod","hamextfingerl","hampalmd","hamnose","hamseqbegin","hamtouch","hamfingertip","hamindexfinger","hamseqend","hamparbegin","hamreplace","hamflathand","hamextfingero","hampalml","hamchest","hamlrat","hambetween","hamchest","hamparend"],
  "sorry":["hamfist", "hamthumbacrossmod", "hamextfingerul", "hambetween", "hamextfingeru", "hampalml", "hamchest", "hamtouch", "hamcirclei", "hamsmallmod"],
  "today":["hamfinger2", "hamextfingerd", "hampalmd", "hamchest", "hamclose", "hammoved", "hamfast", "hamrepeatfromstart"],
  "thankyou":["hamflathand", "hamextfingeru", "hampalmu", "hamchin", "hamseqbegin", "hamtouch", "hamfingerpad", "hammiddlefinger", "hamseqend", "hamreplace", "hamflathand", "hamextfingerol", "hamextfingeruo", "hampalmu", "hamchest"],
  "where":["hamfinger2345", "hamthumboutmod", "hamextfingero", "hambetween", "hamextfingero", "hampalmu", "hamstomach", "hamclose", "hamparbegin", "hamreplace", "hamextfingero", "hambetween", "hamextfingero", "hamstomach", "hamlrat", "hamrepeatfromstart", "hamparend"],
  "who":["hamfinger2", "hamextfingeru", "hampalmu", "hamhead", "hamcircleo", "hamreplace", "hamfinger2345", "hamthumboutmod", "hamextfingero", "hamshoulders", "hamswinging", "hamsmallmod"],
  "with":["hamparbegin", "hamfist", "hamplus", "hamfist", "hamparend", "hamparbegin", "hamextfingero", "hampalml", "hamplus", "hamextfingero", "hampalmr", "hamparend", "hamparbegin", "hampalm", "hamplus", "hampalm", "hamparend", "hamtouch", "hamchest"],
  "yesterday":["hamfinger2", "hamextfingeru", "hampalmu", "hamshoulders", "hamlrat", "hammoveu", "hamlargemod", "hamreplace", "hamextfingeri", "hampalmd"],
  "you":["hamfinger2", "hamthumbacrossmod", "hamextfingero", "hampalml", "hambetween", "hampalmdr", "hamchest", "hammoveo"]
  }
